### ISSUE TITLE
PIR-IPSensor4Hue error compiling

### ISSUE THREAD

**Issue by kolbenhans** [eluinstra/PIR-IPSensor4Hue#1]
Hue_Motion_Sensor:15: error: invalid preprocessing directive #WiFi

 #WiFi

  ^

Hue_Motion_Sensor:19: error: invalid preprocessing directive #Hue

 #Hue

  ^

Hue_Motion_Sensor:25: error: invalid preprocessing directive #Sensor

 #Sensor

  ^

**Comment by eluinstra** [comment]
Those lines should have been comments and not directives. Don't know how they got in there, but I fixed that. Could you try it again?
